[source]
paths = ["src", "tests", "examples"]
includes = ["vendor"]
excludes = [
    "src/bootstrap.php",
    "src/preload.php",
    "src/Psl/Internal/Loader.php",
]

[format]
null_type_hint = "pipe"

[linter]
plugins = ["php-unit"]

[[linter.rules]]
name = "maintainability/cyclomatic-complexity"
threshold = 43

[[linter.rules]]
name = "maintainability/kan-defect"
threshold = 3.5

[[linter.rules]]
name = "maintainability/halstead"
effort_threshold = 16_000.0
volume_threshold = 1_400.0
difficulty_threshold = 18.5

[[linter.rules]]
name = "maintainability/excessive-parameter-list"
threshold = 9

[[linter.rules]]
name = "maintainability/too-many-enum-cases"
threshold = 800

[[linter.rules]]
name = "maintainability/too-many-methods"
threshold = 43

[[linter.rules]]
name = "best-practices/disallowed-functions"
functions = ["is_null", "assert"]

[[linter.rules]]
name = "best-practices/excessive-nesting"
threshold = 5

[[linter.rules]]
name = "best-practices/no-debug-symbols"
level = "Error"

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "Warning"

[[linter.rules]]
name = "strictness/require-constant-type"
level = "Warning"

[[linter.rules]]
name = "strictness/require-parameter-type"
level = "Warning"

[[linter.rules]]
name = "strictness/require-property-type"
level = "Error"

[[linter.rules]]
name = "strictness/require-return-type"
level = "Warning"

[[linter.rules]]
name = "strictness/require-strict-types"
level = "Error"

[[linter.rules]]
name = "safety/no-error-control-operator"
level = "Off"

[[linter.rules]]
name = "safety/no-global"
level = "Warning"
